PROJECT = hello_world
PROJECT_DESCRIPTION = Cowboy Hello World example
PROJECT_VERSION = 2

DEPS = cowboy
# DEPS = cowboy opentelemetry
dep_cowboy_commit = master

# OpenTelemetry dependencies
# dep_opentelemetry = git https://github.com/open-telemetry/opentelemetry-erlang
# dep_opentelemetry_commit = main

REL_DEPS = relx

include ./erlang.mk
