version: '3.7'

volumes:
    data: {}
    grafana_data: {}

services:
    prometheus:
        image: prom/prometheus:v2.15.2
        container_name: prometheus
        volumes:
            - ./config:/etc/prometheus
            - data:/prometheus 
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.enable-lifecycle'
            - '--storage.tsdb.retention.time=7d'
        ports:
            - "9090:9090"
        restart: unless-stopped
    nodeexporter:
        image: prom/node-exporter
        container_name: nodeexporter 
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro 
            - /:/rootfs:ro 
            - /tmp:/tmp:ro 
        command:
            - '--collector.textfile.directory=/tmp'
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - --collector.filesystem.ignored-mount-points
            - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
        ports:
            - "9100:9100"
        restart: unless-stopped